### ISSUE TITLE
Debugging is broken with VS Code 1.60.0 

### ISSUE THREAD

**Issue by buggy** [StackToolbox/aws-sam-webpack-plugin#66]
It looks like [VS Code 1.60.0](https://code.visualstudio.com/updates/v1_60#_javascript-debugging) has made changes that have broken debugging. This needs to be fixed.

**Comment by buggy** [comment]
It looks like VS Code 1.60.0 has problems. Debugging and source maps seem to be broken in general. I found an issue suggesting they might do a 1.60.1 release to fix this. Once that's done I'll look into debugging again.

**Comment by AndrewZelaya** [comment]
I think this was perhaps the issue previously referred to? https://github.com/microsoft/vscode/issues/133310

**Comment by lee-wilkins** [comment]
If anyone else comes across this issue this post https://blog.many-monkeys.com/debugging-lambdas-in-vscode/ helped me solve the issue for any vsCode versions above 1.60

The key is modifying your output block in webpack.config as such
```
output: {
    devtoolModuleFilenameTemplate: '[absolute-resource-path]',
}
```

**Comment by akycop** [comment]
> If anyone else comes across this issue this post https://blog.many-monkeys.com/debugging-lambdas-in-vscode/ helped me solve the issue for any vsCode versions above 1.60
> 
> The key is modifying your output block in webpack.config as such
> 
> ```
> output: {
>     devtoolModuleFilenameTemplate: '[absolute-resource-path]',
> }
> ```

I tried it with Vscode 1.88.1 and it worked fine. Thank you very much.
