### ISSUE TITLE
Add a tag for Nodejs18.x

### ISSUE THREAD

**Issue by sdh100shaun** [StackToolbox/aws-sam-webpack-plugin#85]
I see there has been an update for node18 but cannot see a version release - would you please be able to release a new version?
Is there anything can help with

**Comment by buggy** [comment]
It looks like I didn't create a tag for 0.13.0. That version was published to NPM 5 months ago and includes nodejs18.x support. If you're using the latest version it should work.

**Comment by sdh100shaun** [comment]
Yes it works on latest version
